version: '3.8'

services:
  db:
    image: postgres:15
    container_name: medicore-postgres
    environment:
      POSTGRES_USER: medicore_user
      POSTGRES_PASSWORD: medicore_password
      POSTGRES_DB: medicore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: medicore-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
