apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: medicore-frontend:latest
          imagePullPolicy: Never # For local Docker Desktop
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: medicore-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # For Docker Desktop, this usually gives us localhost mapping
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
