apiVersion: v1
kind: Secret
metadata:
  name: medicore-secret
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: bWVkaWNvcmVfcGFzc3dvcmQ=
  APP_JWTSECRET: VkdocGNwbHpRVk5sWTNKbGRFdGxlVVo2Y2twWFZFRjFkR2hsYm5ScFkyRjBhVzl1UVc1a1NYUlRhRzkxYkdSQ1pVeHZibWRGYm05MVoyaFViMEpsVTJWamRYSmw=
