server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/medicore_db
    username: medicore_user
    password: medicore_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6380

jwt:
  secret: averylongsecretkeyforjwtsignaturethatneedstobeatleast256bitslong12345
  expirationMs: 86400000 # 24 hours
